### ISSUE TITLE
Use perpetuum emoticons for kill-reports

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/OPDiscordBot#4]
Use the perpetuum emoticons for robots if the robot name matches (or is a partial match)
Sequer Mk2 -> :sequer:
(Most of the original nian robot types are available in this - consider only as a supplement to the text)

**Comment by rvincent-nz** [comment]
Doable! Another possibility here is adding reaction emoticons matching each robot involved in the km.

**Comment by MikeJeffers** [comment]
Ah adding reactions to its own post, good idea, helps seed others to add reactions.

Part2: are all kill-messages one kill? or many kills, as found in the last N seconds?
If so, maybe those should be separate messages per kill, so reactions can be added accordingly

**Comment by rvincent-nz** [comment]
Kill messages are individual, and the new kill alert can also be changed so
that it only goes at the top of a new batch.

**Comment by Veritania** [comment]
The custom emojis we have on discord are not well suited for this, as they simply look bad when displayed in the tiny size of an emoji.

PR https://github.com/OpenPerpetuum/OPDiscordBot/pull/13 which introduced Embeds as kill messages currently use 🤖 in front of the robot name.

If we got some highly stylized icons that would be recognizable at this size we could swap out the generic 🤖  for that.
