### ISSUE TITLE
Better/More Clear separation between kills in single message

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/OPDiscordBot#5]
=======New Kill!========= 
is ok but doesn't cut it and is 'busy'
Better use of whitespace?

**Comment by Veritania** [comment]
Could using the Discord Embeds feature be worth exploring?
Example:
![embed-example](https://user-images.githubusercontent.com/6807104/111012013-b54faf80-839b-11eb-8878-2c721ddb215d.png)

The embed example was quickly thrown together using https://cog-creators.github.io/discord-embed-sandbox/ , but I think you have even more control and options over the embed through code than this sandbox gives you.

For directly addressing the issue of this ticket, the red line in the example can get a random color pr message, so it's easier to see where one kill report starts/ends.

**Comment by MikeJeffers** [comment]
Yes, think something like this would be a good enhancement!
Basically anything that is better communicating the information is a win.
The embed is a nice idea because it will make layout data in 2D a little more maintainable, lines of text was our MVP 😆

**Comment by Veritania** [comment]
I gave it a shot, but ran into an issue that I can't quite figure out at the moment. Please have a look in PR #13 for more details, and examples of the current Embed Look :)

Next day Edit: Aforementioned issue has been fixed, sleep is magic.

**Comment by Veritania** [comment]
Solved with PR https://github.com/OpenPerpetuum/OPDiscordBot/pull/13
