### ISSUE TITLE
Periodically post customizable links

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/OPDiscordBot#6]
As another latent process, only if it hasn't posted this link since the latest report, the bot should post a link to the killboard website, or our other 3rd party killboard websites.

Design it such that:
A kill is posted.
A few minutes pass
"See more details at https://killboard.openperpetuum.com"
days pass, no kills, no further posting of links or text
A kill is posted
A few minutes
" link" (you get it)

Be sure to handle the case of multiple kills popping up periodically.  The latest kill may want to "reset" the timer to post this link.
And think about this link as a way to keep the channel active during downtimes in pvp, and keep the killboard link in view of players looking at the channel.

**Comment by rvincent-nz** [comment]
This was actually a feature in an earlier version, but neither of the killboards I looked at actually allowed for directly linking to kills in question - direct links to the first-party one would just fail, and the flyhub.ru one doesn't seem to have direct links at all. If we're okay with just linking to the kb itself, that's doable.

**Comment by MikeJeffers** [comment]
That's what I mean, and yes it is sad that there is not (yet) a killboard website that has static links per kill.  (However that is very doable!! Just need other 3rd party/team members that want to do it)

**Comment by Veritania** [comment]
No longer a necessary feature, as it's partly solved in PR https://github.com/OpenPerpetuum/OPDiscordBot/pull/13
Each kill message now contains a link to a specific kill on the killboard
