### ISSUE TITLE
Agent kill details: refinements

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/OPDiscordBot#7]
`Agent: Multiplicity, Robot: Callisto, Damage: 0.0000, 7`
Agent participant info needs some name fields added, omit fields with 0, limit significant digits, etc.
Refine as you see fit such that the report reads more clearly and might look like:
`Agent: Multiplicity, Robot: Callisto, ECM: 7 ...`

**Comment by MikeJeffers** [comment]
https://github.com/OpenPerpetuum/OPDiscordBot/blob/master/cogs/perpetuum_killboard_cog.py#L122-L134

**Comment by Veritania** [comment]
Solved with PR https://github.com/OpenPerpetuum/OPDiscordBot/pull/13
